// Marks this module as server-only. If a "use client" component imports it,
// even transitively, the build fails instead of silently shipping data to the
// browser. See docs/SECURITY.md §4.
import "server-only";

import type {
  ActivityItem,
  SessionUser,
  CalendarEvent,
  Client,
  Conversation,
  CrmDocument,
  Deal,
  Lead,
  Message,
  Notification,
  Property,
  Task,
  TeamMember,
} from "@/types";

/**
 * Static fixtures for the prototype. Everything here is invented sample data —
 * no network, no persistence. Values are hand-picked rather than randomised so
 * the UI renders identically on the server and the client.
 */

export const team: Record<string, TeamMember> = {
  avery: { id: "u1", name: "Avery Chen", initials: "AC", role: "Managing Broker", hue: 268 },
  marcus: { id: "u2", name: "Marcus Delgado", initials: "MD", role: "Senior Agent", hue: 200 },
  priya: { id: "u3", name: "Priya Raman", initials: "PR", role: "Listing Agent", hue: 152 },
  jonah: { id: "u4", name: "Jonah Whitfield", initials: "JW", role: "Buyer's Agent", hue: 30 },
  sofia: { id: "u5", name: "Sofia Kowalski", initials: "SK", role: "Transaction Coordinator", hue: 340 },
  dmitri: { id: "u6", name: "Dmitri Volkov", initials: "DV", role: "Agent", hue: 78 },
};

export const currentUser: SessionUser = {
  ...team.avery,
  email: "avery.chen@vantagerealty.com",
};

export const contacts: Record<string, TeamMember> = {
  harper: { id: "c1", name: "Harper Lindqvist", initials: "HL", role: "Buyer", hue: 268 },
  omar: { id: "c2", name: "Omar Haddad", initials: "OH", role: "Seller", hue: 200 },
  yuki: { id: "c3", name: "Yuki Tanaka", initials: "YT", role: "Investor", hue: 152 },
  rosa: { id: "c4", name: "Rosa Villanueva", initials: "RV", role: "Buyer", hue: 30 },
  theo: { id: "c5", name: "Theo Bergström", initials: "TB", role: "Buyer", hue: 340 },
  nadia: { id: "c6", name: "Nadia Okonkwo", initials: "NO", role: "Seller", hue: 78 },
};

/* ------------------------------------------------------------------ leads */

export const leads: Lead[] = [
  {
    id: "L-2041",
    name: "Harper Lindqvist",
    email: "harper.l@fastmail.com",
    phone: "(415) 555-0142",
    stage: "qualified",
    source: "Zillow",
    temperature: "hot",
    score: 92,
    budget: [850000, 1100000],
    location: "Noe Valley, SF",
    owner: team.marcus,
    createdAt: "Jul 14, 2026",
    lastTouch: "2 hours ago",
    tags: ["Pre-approved", "Relocating"],
  },
  {
    id: "L-2038",
    name: "Theo Bergström",
    email: "t.bergstrom@proton.me",
    phone: "(415) 555-0198",
    stage: "touring",
    source: "Referral",
    temperature: "hot",
    score: 88,
    budget: [1200000, 1600000],
    location: "Pacific Heights, SF",
    owner: team.jonah,
    createdAt: "Jul 12, 2026",
    lastTouch: "Yesterday",
    tags: ["Cash buyer"],
  },
  {
    id: "L-2035",
    name: "Rosa Villanueva",
    email: "rosa.villanueva@gmail.com",
    phone: "(510) 555-0177",
    stage: "contacted",
    source: "Open House",
    temperature: "warm",
    score: 71,
    budget: [600000, 780000],
    location: "Rockridge, Oakland",
    owner: team.priya,
    createdAt: "Jul 11, 2026",
    lastTouch: "3 days ago",
    tags: ["First-time buyer"],
  },
  {
    id: "L-2033",
    name: "Yuki Tanaka",
    email: "yuki@tanakaholdings.co",
    phone: "(650) 555-0121",
    stage: "qualified",
    source: "Website",
    temperature: "hot",
    score: 95,
    budget: [2000000, 3500000],
    location: "Palo Alto",
    owner: team.avery,
    createdAt: "Jul 9, 2026",
    lastTouch: "5 hours ago",
    tags: ["Investor", "Multi-unit", "Repeat"],
  },
  {
    id: "L-2029",
    name: "Callum Byrne",
    email: "cbyrne@outlook.com",
    phone: "(415) 555-0165",
    stage: "new",
    source: "Instagram",
    temperature: "warm",
    score: 64,
    budget: [500000, 650000],
    location: "Sunset District, SF",
    owner: team.dmitri,
    createdAt: "Jul 8, 2026",
    lastTouch: "Never",
    tags: [],
  },
  {
    id: "L-2027",
    name: "Ines Moreau",
    email: "ines.moreau@mail.fr",
    phone: "(415) 555-0133",
    stage: "contacted",
    source: "Realtor.com",
    temperature: "warm",
    score: 76,
    budget: [900000, 1150000],
    location: "Mission District, SF",
    owner: team.marcus,
    createdAt: "Jul 6, 2026",
    lastTouch: "6 days ago",
    tags: ["Needs financing"],
  },
  {
    id: "L-2022",
    name: "Devon Pritchard",
    email: "devon.p@workmail.com",
    phone: "(925) 555-0189",
    stage: "unqualified",
    source: "Cold Call",
    temperature: "cold",
    score: 28,
    budget: [300000, 400000],
    location: "Walnut Creek",
    owner: team.dmitri,
    createdAt: "Jul 2, 2026",
    lastTouch: "2 weeks ago",
    tags: ["Budget mismatch"],
  },
  {
    id: "L-2019",
    name: "Amara Osei",
    email: "amara.osei@gmail.com",
    phone: "(415) 555-0154",
    stage: "touring",
    source: "Referral",
    temperature: "hot",
    score: 84,
    budget: [1000000, 1300000],
    location: "Bernal Heights, SF",
    owner: team.priya,
    createdAt: "Jun 28, 2026",
    lastTouch: "Yesterday",
    tags: ["Pre-approved", "Urgent"],
  },
];

/* ---------------------------------------------------------------- clients */

export const clients: Client[] = [
  {
    id: "C-1180",
    name: "Omar Haddad",
    email: "omar.haddad@icloud.com",
    phone: "(415) 555-0111",
    type: "seller",
    status: "under-contract",
    lifetimeValue: 2450000,
    properties: 2,
    owner: team.avery,
    since: "Mar 2024",
    location: "Presidio Heights, SF",
  },
  {
    id: "C-1176",
    name: "Yuki Tanaka",
    email: "yuki@tanakaholdings.co",
    phone: "(650) 555-0121",
    type: "investor",
    status: "active",
    lifetimeValue: 8900000,
    properties: 7,
    owner: team.avery,
    since: "Sep 2022",
    location: "Palo Alto",
  },
  {
    id: "C-1171",
    name: "Nadia Okonkwo",
    email: "n.okonkwo@gmail.com",
    phone: "(415) 555-0102",
    type: "seller",
    status: "active",
    lifetimeValue: 1320000,
    properties: 1,
    owner: team.priya,
    since: "Jan 2026",
    location: "Glen Park, SF",
  },
  {
    id: "C-1164",
    name: "Harper Lindqvist",
    email: "harper.l@fastmail.com",
    phone: "(415) 555-0142",
    type: "buyer",
    status: "active",
    lifetimeValue: 0,
    properties: 0,
    owner: team.marcus,
    since: "Jul 2026",
    location: "Noe Valley, SF",
  },
  {
    id: "C-1158",
    name: "Grant & Eloise Mbeki",
    email: "mbeki.family@mail.com",
    phone: "(510) 555-0196",
    type: "buyer",
    status: "closed",
    lifetimeValue: 985000,
    properties: 1,
    owner: team.jonah,
    since: "Nov 2025",
    location: "Alameda",
  },
  {
    id: "C-1149",
    name: "Sebastian Duarte",
    email: "sduarte@duartecap.com",
    phone: "(415) 555-0173",
    type: "investor",
    status: "dormant",
    lifetimeValue: 4100000,
    properties: 3,
    owner: team.marcus,
    since: "Jun 2021",
    location: "SoMa, SF",
  },
  {
    id: "C-1142",
    name: "Lena Fitzgerald",
    email: "lena.fitz@hey.com",
    phone: "(415) 555-0128",
    type: "renter",
    status: "active",
    lifetimeValue: 0,
    properties: 0,
    owner: team.dmitri,
    since: "May 2026",
    location: "Hayes Valley, SF",
  },
];

/* ------------------------------------------------------------- properties */

export const properties: Property[] = [
  {
    id: "P-780",
    title: "Restored Edwardian with garden",
    address: "1428 Sanchez Street",
    city: "San Francisco",
    state: "CA",
    zip: "94131",
    price: 1895000,
    status: "active",
    type: "Single Family",
    beds: 4,
    baths: 3,
    sqft: 2840,
    lotSize: "0.09 ac",
    yearBuilt: 1912,
    daysOnMarket: 12,
    views: 3421,
    saves: 187,
    agent: team.priya,
    hue: 268,
  },
  {
    id: "P-776",
    title: "Corner penthouse, bay views",
    address: "88 Townsend Street, PH2",
    city: "San Francisco",
    state: "CA",
    zip: "94107",
    price: 3250000,
    status: "pending",
    type: "Condo",
    beds: 3,
    baths: 3,
    sqft: 2210,
    lotSize: "—",
    yearBuilt: 2019,
    daysOnMarket: 34,
    views: 8902,
    saves: 512,
    agent: team.avery,
    hue: 205,
  },
  {
    id: "P-771",
    title: "Mid-century on a quiet cul-de-sac",
    address: "62 Laurel Grove Court",
    city: "Oakland",
    state: "CA",
    zip: "94618",
    price: 1145000,
    status: "active",
    type: "Single Family",
    beds: 3,
    baths: 2,
    sqft: 1760,
    lotSize: "0.14 ac",
    yearBuilt: 1958,
    daysOnMarket: 5,
    views: 1204,
    saves: 63,
    agent: team.jonah,
    hue: 152,
  },
  {
    id: "P-765",
    title: "Six-unit income property",
    address: "2201 Folsom Street",
    city: "San Francisco",
    state: "CA",
    zip: "94110",
    price: 4600000,
    status: "coming-soon",
    type: "Multi-Family",
    beds: 12,
    baths: 8,
    sqft: 7400,
    lotSize: "0.18 ac",
    yearBuilt: 1974,
    daysOnMarket: 0,
    views: 342,
    saves: 41,
    agent: team.marcus,
    hue: 78,
  },
  {
    id: "P-758",
    title: "Sunlit townhouse near the park",
    address: "319 Cole Street, Unit B",
    city: "San Francisco",
    state: "CA",
    zip: "94117",
    price: 1425000,
    status: "sold",
    type: "Townhouse",
    beds: 3,
    baths: 2,
    sqft: 1580,
    lotSize: "—",
    yearBuilt: 1996,
    daysOnMarket: 21,
    views: 5610,
    saves: 298,
    agent: team.priya,
    hue: 340,
  },
  {
    id: "P-752",
    title: "Hillside lot with approved plans",
    address: "0 Ridgecrest Way",
    city: "Mill Valley",
    state: "CA",
    zip: "94941",
    price: 890000,
    status: "active",
    type: "Land",
    beds: 0,
    baths: 0,
    sqft: 0,
    lotSize: "1.2 ac",
    yearBuilt: 0,
    daysOnMarket: 67,
    views: 780,
    saves: 22,
    agent: team.dmitri,
    hue: 30,
  },
  {
    id: "P-747",
    title: "Ground-floor retail, high foot traffic",
    address: "540 Valencia Street",
    city: "San Francisco",
    state: "CA",
    zip: "94110",
    price: 2750000,
    status: "off-market",
    type: "Commercial",
    beds: 0,
    baths: 2,
    sqft: 3100,
    lotSize: "0.07 ac",
    yearBuilt: 1948,
    daysOnMarket: 0,
    views: 156,
    saves: 8,
    agent: team.avery,
    hue: 12,
  },
  {
    id: "P-740",
    title: "Loft conversion with mezzanine",
    address: "1150 Harrison Street, #305",
    city: "San Francisco",
    state: "CA",
    zip: "94103",
    price: 1080000,
    status: "active",
    type: "Condo",
    beds: 2,
    baths: 2,
    sqft: 1440,
    lotSize: "—",
    yearBuilt: 2004,
    daysOnMarket: 9,
    views: 2310,
    saves: 119,
    agent: team.jonah,
    hue: 240,
  },
];

/* ------------------------------------------------------------------ deals */

export const deals: Deal[] = [
  {
    id: "D-410",
    title: "1428 Sanchez — Lindqvist purchase",
    client: "Harper Lindqvist",
    property: "1428 Sanchez Street",
    value: 1895000,
    commission: 47375,
    stage: "showing",
    probability: 35,
    closeDate: "Sep 30, 2026",
    owner: team.marcus,
    priority: "high",
  },
  {
    id: "D-408",
    title: "88 Townsend PH2 — Haddad sale",
    client: "Omar Haddad",
    property: "88 Townsend Street, PH2",
    value: 3250000,
    commission: 81250,
    stage: "under-contract",
    probability: 85,
    closeDate: "Aug 14, 2026",
    owner: team.avery,
    priority: "high",
  },
  {
    id: "D-405",
    title: "Folsom six-plex — Tanaka acquisition",
    client: "Yuki Tanaka",
    property: "2201 Folsom Street",
    value: 4600000,
    commission: 92000,
    stage: "offer",
    probability: 60,
    closeDate: "Oct 8, 2026",
    owner: team.avery,
    priority: "high",
  },
  {
    id: "D-402",
    title: "62 Laurel Grove — Villanueva purchase",
    client: "Rosa Villanueva",
    property: "62 Laurel Grove Court",
    value: 1145000,
    commission: 28625,
    stage: "qualification",
    probability: 15,
    closeDate: "Nov 20, 2026",
    owner: team.priya,
    priority: "medium",
  },
  {
    id: "D-399",
    title: "319 Cole B — Mbeki purchase",
    client: "Grant & Eloise Mbeki",
    property: "319 Cole Street, Unit B",
    value: 1425000,
    commission: 35625,
    stage: "closed-won",
    probability: 100,
    closeDate: "Jul 2, 2026",
    owner: team.jonah,
    priority: "medium",
  },
  {
    id: "D-396",
    title: "Glen Park listing — Okonkwo",
    client: "Nadia Okonkwo",
    property: "740 Chenery Street",
    value: 1320000,
    commission: 33000,
    stage: "closing",
    probability: 92,
    closeDate: "Jul 29, 2026",
    owner: team.priya,
    priority: "high",
  },
  {
    id: "D-392",
    title: "1150 Harrison #305 — Bergström purchase",
    client: "Theo Bergström",
    property: "1150 Harrison Street, #305",
    value: 1080000,
    commission: 27000,
    stage: "showing",
    probability: 40,
    closeDate: "Sep 12, 2026",
    owner: team.jonah,
    priority: "medium",
  },
  {
    id: "D-388",
    title: "Ridgecrest lot — Duarte investment",
    client: "Sebastian Duarte",
    property: "0 Ridgecrest Way",
    value: 890000,
    commission: 22250,
    stage: "qualification",
    probability: 10,
    closeDate: "Dec 15, 2026",
    owner: team.dmitri,
    priority: "low",
  },
  {
    id: "D-385",
    title: "540 Valencia — retail assemblage",
    client: "Yuki Tanaka",
    property: "540 Valencia Street",
    value: 2750000,
    commission: 55000,
    stage: "offer",
    probability: 55,
    closeDate: "Oct 30, 2026",
    owner: team.marcus,
    priority: "medium",
  },
  {
    id: "D-381",
    title: "Alameda duplex — Osei purchase",
    client: "Amara Osei",
    property: "1207 Pacific Avenue",
    value: 1210000,
    commission: 30250,
    stage: "under-contract",
    probability: 78,
    closeDate: "Aug 25, 2026",
    owner: team.priya,
    priority: "high",
  },
];

/* ------------------------------------------------------------------ tasks */

export const tasks: Task[] = [
  {
    id: "T-920",
    title: "Send comparable analysis to Harper",
    description: "Pull three closed comps within 0.5 miles of 1428 Sanchez.",
    status: "in-progress",
    priority: "high",
    dueDate: "Today, 4:00 PM",
    assignee: team.marcus,
    relatedTo: "D-410",
    list: "follow-up",
  },
  {
    id: "T-918",
    title: "Collect signed disclosure packet — Haddad",
    status: "blocked",
    priority: "urgent",
    dueDate: "Today, 6:00 PM",
    assignee: team.sofia,
    relatedTo: "D-408",
    list: "paperwork",
  },
  {
    id: "T-915",
    title: "Confirm Saturday open house staging",
    description: "Vendor walkthrough at 9am, photographer arrives 11am.",
    status: "todo",
    priority: "medium",
    dueDate: "Tomorrow",
    assignee: team.priya,
    relatedTo: "P-780",
    list: "showings",
  },
  {
    id: "T-911",
    title: "Draft July newsletter for past clients",
    status: "todo",
    priority: "low",
    dueDate: "Jul 24, 2026",
    assignee: team.dmitri,
    list: "marketing",
  },
  {
    id: "T-908",
    title: "Schedule inspection — 62 Laurel Grove",
    status: "todo",
    priority: "high",
    dueDate: "Jul 22, 2026",
    assignee: team.jonah,
    relatedTo: "D-402",
    list: "paperwork",
  },
  {
    id: "T-904",
    title: "Follow up with Ines Moreau on financing",
    status: "todo",
    priority: "medium",
    dueDate: "Jul 21, 2026",
    assignee: team.marcus,
    relatedTo: "L-2027",
    list: "follow-up",
  },
  {
    id: "T-899",
    title: "Upload final closing statement — Mbeki",
    status: "done",
    priority: "medium",
    dueDate: "Jul 3, 2026",
    assignee: team.sofia,
    relatedTo: "D-399",
    list: "paperwork",
  },
  {
    id: "T-895",
    title: "Order new listing photography — Folsom",
    status: "in-progress",
    priority: "medium",
    dueDate: "Jul 23, 2026",
    assignee: team.priya,
    relatedTo: "P-765",
    list: "marketing",
  },
  {
    id: "T-890",
    title: "Private showing prep — Bergström",
    status: "done",
    priority: "high",
    dueDate: "Jul 18, 2026",
    assignee: team.jonah,
    relatedTo: "D-392",
    list: "showings",
  },
];

/* --------------------------------------------------------------- calendar */

export const calendarEvents: CalendarEvent[] = [
  {
    id: "E-1",
    title: "Showing — 1428 Sanchez",
    kind: "showing",
    date: "2026-07-20",
    start: "10:00",
    end: "11:00",
    location: "1428 Sanchez St",
    attendees: [team.marcus, contacts.harper],
  },
  {
    id: "E-2",
    title: "Buyer consult — Villanueva",
    kind: "call",
    date: "2026-07-20",
    start: "13:30",
    end: "14:00",
    attendees: [team.priya, contacts.rosa],
  },
  {
    id: "E-3",
    title: "Pipeline review",
    kind: "internal",
    date: "2026-07-20",
    start: "16:00",
    end: "17:00",
    location: "Conference room A",
    attendees: [team.avery, team.marcus, team.priya, team.jonah],
  },
  {
    id: "E-4",
    title: "Inspection — 62 Laurel Grove",
    kind: "showing",
    date: "2026-07-22",
    start: "09:00",
    end: "12:00",
    location: "62 Laurel Grove Ct",
    attendees: [team.jonah],
  },
  {
    id: "E-5",
    title: "Closing — Okonkwo listing",
    kind: "closing",
    date: "2026-07-29",
    start: "11:00",
    end: "12:30",
    location: "Bay Title, 400 Montgomery",
    attendees: [team.priya, team.sofia, contacts.nadia],
  },
  {
    id: "E-6",
    title: "Open house — 1428 Sanchez",
    kind: "open-house",
    date: "2026-07-25",
    start: "13:00",
    end: "16:00",
    location: "1428 Sanchez St",
    attendees: [team.priya, team.dmitri],
  },
  {
    id: "E-7",
    title: "Offer review — Tanaka / Folsom",
    kind: "call",
    date: "2026-07-23",
    start: "15:00",
    end: "16:00",
    attendees: [team.avery, contacts.yuki],
  },
  {
    id: "E-8",
    title: "Listing presentation — Duarte",
    kind: "internal",
    date: "2026-07-27",
    start: "10:30",
    end: "11:30",
    location: "540 Valencia St",
    attendees: [team.marcus],
  },
  {
    id: "E-9",
    title: "Showing — 1150 Harrison #305",
    kind: "showing",
    date: "2026-07-21",
    start: "17:30",
    end: "18:15",
    location: "1150 Harrison St",
    attendees: [team.jonah, contacts.theo],
  },
];

/* --------------------------------------------------------------- messages */

export const conversations: Conversation[] = [
  {
    id: "M-1",
    contact: contacts.harper,
    channel: "sms",
    preview: "Perfect — is Saturday morning still open for the second walkthrough?",
    timestamp: "9:41 AM",
    unread: 2,
    pinned: true,
  },
  {
    id: "M-2",
    contact: contacts.omar,
    channel: "email",
    preview: "Attaching the signed addendum. Let me know if the title company needs…",
    timestamp: "8:15 AM",
    unread: 0,
    pinned: true,
  },
  {
    id: "M-3",
    contact: contacts.yuki,
    channel: "email",
    preview: "What are the current cap rates on the Folsom building? I want to model…",
    timestamp: "Yesterday",
    unread: 1,
  },
  {
    id: "M-4",
    contact: contacts.rosa,
    channel: "sms",
    preview: "Thanks for sending those over! I'll look tonight.",
    timestamp: "Yesterday",
    unread: 0,
  },
  {
    id: "M-5",
    contact: contacts.theo,
    channel: "whatsapp",
    preview: "Can we push the Tuesday showing to 6pm?",
    timestamp: "Jul 18",
    unread: 0,
  },
  {
    id: "M-6",
    contact: contacts.nadia,
    channel: "email",
    preview: "The buyers' inspector flagged the water heater — how do we respond?",
    timestamp: "Jul 17",
    unread: 0,
  },
];

export const messageThread: Message[] = [
  {
    id: "t1",
    author: "them",
    body: "Hi! We toured 1428 Sanchez yesterday and both really loved it.",
    timestamp: "9:12 AM",
  },
  {
    id: "t2",
    author: "me",
    body: "That's great to hear. It photographs well but the garden is the real story — glad you got to see it in person.",
    timestamp: "9:20 AM",
    status: "read",
  },
  {
    id: "t3",
    author: "them",
    body: "Agreed. My partner wants one more look before we talk numbers. Do you have comps for the block?",
    timestamp: "9:33 AM",
  },
  {
    id: "t4",
    author: "me",
    body: "I'm pulling three closed comps within half a mile now. I'll send them over this afternoon.",
    timestamp: "9:38 AM",
    status: "delivered",
  },
  {
    id: "t5",
    author: "them",
    body: "Perfect — is Saturday morning still open for the second walkthrough?",
    timestamp: "9:41 AM",
  },
];

/* -------------------------------------------------------------- documents */

export const documents: CrmDocument[] = [
  {
    id: "DOC-501",
    name: "Purchase Agreement — 88 Townsend PH2.pdf",
    kind: "contract",
    size: "2.4 MB",
    owner: team.sofia,
    updatedAt: "2 hours ago",
    status: "awaiting-signature",
    relatedTo: "D-408",
  },
  {
    id: "DOC-498",
    name: "Seller Disclosure Packet — Haddad.pdf",
    kind: "disclosure",
    size: "8.1 MB",
    owner: team.sofia,
    updatedAt: "Yesterday",
    status: "signed",
    relatedTo: "D-408",
  },
  {
    id: "DOC-494",
    name: "Inspection Report — 62 Laurel Grove.pdf",
    kind: "inspection",
    size: "5.7 MB",
    owner: team.jonah,
    updatedAt: "Jul 18, 2026",
    status: "draft",
    relatedTo: "D-402",
  },
  {
    id: "DOC-490",
    name: "Listing Agreement — 2201 Folsom.docx",
    kind: "listing",
    size: "412 KB",
    owner: team.marcus,
    updatedAt: "Jul 16, 2026",
    status: "signed",
    relatedTo: "P-765",
  },
  {
    id: "DOC-486",
    name: "Closing Statement — Mbeki.pdf",
    kind: "financial",
    size: "1.1 MB",
    owner: team.sofia,
    updatedAt: "Jul 3, 2026",
    status: "signed",
    relatedTo: "D-399",
  },
  {
    id: "DOC-482",
    name: "Lead-Based Paint Disclosure — Sanchez.pdf",
    kind: "disclosure",
    size: "680 KB",
    owner: team.priya,
    updatedAt: "Jul 2, 2026",
    status: "expired",
    relatedTo: "P-780",
  },
  {
    id: "DOC-477",
    name: "Proof of Funds — Tanaka Holdings.pdf",
    kind: "financial",
    size: "240 KB",
    owner: team.avery,
    updatedAt: "Jun 29, 2026",
    status: "signed",
    relatedTo: "D-405",
  },
];

/* ---------------------------------------------------------- notifications */

export const notifications: Notification[] = [
  {
    id: "N-1",
    title: "Offer accepted on 88 Townsend PH2",
    body: "Omar Haddad's counter was accepted at $3,250,000. Contingency period starts today.",
    timestamp: "12 minutes ago",
    read: false,
    category: "deal",
  },
  {
    id: "N-2",
    title: "New high-intent lead",
    body: "Harper Lindqvist scored 92 — pre-approved and actively touring in Noe Valley.",
    timestamp: "2 hours ago",
    read: false,
    category: "lead",
  },
  {
    id: "N-3",
    title: "Sofia Kowalski mentioned you",
    body: "\"@Avery the disclosure packet is blocked until we get the HOA docs.\"",
    timestamp: "3 hours ago",
    read: false,
    category: "mention",
  },
  {
    id: "N-4",
    title: "Task due today",
    body: "Send comparable analysis to Harper — due 4:00 PM.",
    timestamp: "5 hours ago",
    read: true,
    category: "task",
  },
  {
    id: "N-5",
    title: "Document expired",
    body: "Lead-Based Paint Disclosure for 1428 Sanchez needs to be re-issued.",
    timestamp: "Yesterday",
    read: true,
    category: "system",
  },
  {
    id: "N-6",
    title: "Showing confirmed",
    body: "Theo Bergström confirmed 1150 Harrison #305 for Jul 21 at 5:30 PM.",
    timestamp: "Yesterday",
    read: true,
    category: "deal",
  },
  {
    id: "N-7",
    title: "Weekly pipeline report ready",
    body: "Your team closed $1.4M in volume last week, up 12% week over week.",
    timestamp: "Jul 18, 2026",
    read: true,
    category: "system",
  },
];

/* ---------------------------------------------------------------- activity */

export const activity: ActivityItem[] = [
  {
    id: "A-1",
    actor: team.avery,
    action: "moved a deal to",
    target: "Under contract",
    timestamp: "12m ago",
  },
  {
    id: "A-2",
    actor: team.priya,
    action: "logged a showing on",
    target: "1428 Sanchez Street",
    timestamp: "1h ago",
  },
  {
    id: "A-3",
    actor: team.sofia,
    action: "requested signatures on",
    target: "Purchase Agreement — 88 Townsend",
    timestamp: "2h ago",
  },
  {
    id: "A-4",
    actor: team.marcus,
    action: "added a note to",
    target: "Harper Lindqvist",
    timestamp: "3h ago",
  },
  {
    id: "A-5",
    actor: team.jonah,
    action: "created a task",
    target: "Schedule inspection — 62 Laurel Grove",
    timestamp: "5h ago",
  },
  {
    id: "A-6",
    actor: team.dmitri,
    action: "imported 14 leads from",
    target: "Instagram campaign",
    timestamp: "Yesterday",
  },
];

/* ------------------------------------------------------------------ charts */

export const revenueByMonth = [
  { month: "Jan", closed: 2.1, pipeline: 4.4 },
  { month: "Feb", closed: 2.8, pipeline: 5.1 },
  { month: "Mar", closed: 3.6, pipeline: 5.9 },
  { month: "Apr", closed: 3.1, pipeline: 6.8 },
  { month: "May", closed: 4.2, pipeline: 7.2 },
  { month: "Jun", closed: 5.4, pipeline: 8.1 },
  { month: "Jul", closed: 4.9, pipeline: 9.4 },
];

export const leadsBySource = [
  { source: "Zillow", count: 142 },
  { source: "Referral", count: 118 },
  { source: "Website", count: 96 },
  { source: "Open House", count: 64 },
  { source: "Instagram", count: 51 },
  { source: "Realtor.com", count: 37 },
];

export const conversionFunnel = [
  { stage: "Leads", value: 508 },
  { stage: "Contacted", value: 341 },
  { stage: "Qualified", value: 186 },
  { stage: "Touring", value: 94 },
  { stage: "Offer", value: 43 },
  { stage: "Closed", value: 27 },
];

export const dealMix = [
  { name: "Single Family", value: 38, fill: "var(--color-chart-1)" },
  { name: "Condo", value: 27, fill: "var(--color-chart-2)" },
  { name: "Multi-Family", value: 18, fill: "var(--color-chart-3)" },
  { name: "Commercial", value: 11, fill: "var(--color-chart-4)" },
  { name: "Land", value: 6, fill: "var(--color-chart-5)" },
];

export const agentLeaderboard = [
  { agent: team.avery, volume: 12400000, deals: 9, winRate: 42 },
  { agent: team.priya, volume: 8750000, deals: 11, winRate: 38 },
  { agent: team.marcus, volume: 7300000, deals: 7, winRate: 35 },
  { agent: team.jonah, volume: 5100000, deals: 8, winRate: 31 },
  { agent: team.dmitri, volume: 2400000, deals: 4, winRate: 22 },
];
