"""Envelope encryption for secrets stored in the database.

Phase 5.6. This is what `app/models/user.py` deferred when it said the TOTP
secret is "stored as issued, and that is a stated trade-off": encryption at rest
for a column needs a key managed somewhere other than beside the data, and this
module is that somewhere.

## The shape

A `KeyProvider` produces and unwraps **data keys**; a `SecretBox` uses them to
seal values. Two providers ship:

  * `LocalKeyProvider` — keys from configuration. Correct cryptography, ordinary
    key management: the key lives in the process's environment, so a compromise
    that reads the environment reads the key. Honest for local and staging.
  * `AwsKmsKeyProvider` — envelope encryption against KMS. The data key is
    generated by KMS, used once, and stored **wrapped** alongside the
    ciphertext; the plaintext data key never touches disk and unwrapping it
    requires an IAM call that CloudTrail records.

Both are behind a `Protocol`, the same shape `ObjectStorage` and the email
provider use, so business logic never imports boto3 or a key.

## What this is and is not

It protects **a database dump**. Someone with a backup, a replica, or a stolen
snapshot gets ciphertext. It does not protect against an attacker executing code
in the API process, who can simply ask the box to decrypt — no field-level
scheme can, and claiming otherwise is how a "we encrypt everything" bullet point
becomes a false sense of security.

## The token format

    vnt1.<key_id>.<wrapped_key_b64>.<nonce_b64>.<ciphertext_b64>

Self-describing on purpose. The key id travels **with** the value, so rotating
the active key does not require rewriting every existing row: new writes use the
new key, old reads unwrap with the old one, and a background rewrite can happen
whenever it happens rather than as a migration that must not fail.

AES-256-GCM: authenticated, so a tampered ciphertext fails loudly instead of
decrypting to plausible garbage. The token's own prefix is part of the
associated data, which is what stops a value being lifted from one column and
replayed into another.

## Legacy plaintext

`decrypt` accepts a value that is not a token and returns it unchanged. That is
deliberate and is the migration path: this feature ships onto a database that
already holds plaintext TOTP secrets, and refusing to read them would lock every
enrolled user out of their own account at deploy time. The value is re-sealed on
the next write, so the plaintext population drains rather than being rewritten
by a migration that has no key access and cannot be rolled back.
"""

from __future__ import annotations

import base64
import os
from dataclasses import dataclass
from functools import lru_cache
from typing import Protocol, runtime_checkable

from app.core.config import Settings, get_settings
from app.core.logging import get_logger

logger = get_logger(__name__)

#: Version tag. A future format change gets `vnt2`, and `decrypt` can keep
#: reading `vnt1` for as long as any row still holds one.
TOKEN_PREFIX = "vnt1"  # noqa: S105 — a format tag, not a secret

#: AES-256. Not configurable: an algorithm choice exposed as a setting is a
#: downgrade attack with a config file for a payload.
KEY_BYTES = 32
NONCE_BYTES = 12

#: Key id for the JWT_SECRET-derived fallback. Visible in every token it seals,
#: so "why can nothing be decrypted since we rotated JWT_SECRET" has an answer
#: written on the data.
DERIVED_KEY_ID = "jwt-derived"


class SecretsError(Exception):
    """Key management or sealing failed."""


@dataclass(frozen=True, slots=True)
class DataKey:
    """A single-use key, plus whatever is needed to get it back.

    `wrapped` is what gets stored. For KMS it is the encrypted blob; for the
    local provider it is empty, because the key is the configured one and the
    key id alone identifies it.
    """

    key_id: str
    plaintext: bytes
    wrapped: bytes


@runtime_checkable
class KeyProvider(Protocol):
    name: str

    def generate(self) -> DataKey:
        """A fresh data key for one encryption."""
        ...

    def unwrap(self, key_id: str, wrapped: bytes) -> bytes:
        """Recover the plaintext data key for a stored value."""
        ...


class LocalKeyProvider:
    """Keys from configuration.

    The cryptography is real; the key management is ordinary. Anything that can
    read the process environment can read the key, which is exactly the same
    exposure `JWT_SECRET` has — so this is honest for local and staging, and
    production is expected to configure KMS.

    Supports more than one key so a rotation is a config change rather than a
    migration: `ENCRYPTION_KEYS` maps id to material, `ENCRYPTION_ACTIVE_KEY_ID`
    picks the one new writes use, and old ids stay readable.
    """

    name = "local"

    def __init__(self, keys: dict[str, bytes], active_key_id: str) -> None:
        if active_key_id not in keys:
            raise SecretsError(
                f"ENCRYPTION_ACTIVE_KEY_ID '{active_key_id}' is not among the "
                f"configured keys ({', '.join(sorted(keys)) or 'none'})"
            )
        self._keys = keys
        self._active = active_key_id

    def generate(self) -> DataKey:
        # No wrapped blob: the key id identifies a configured key, so there is
        # nothing to store alongside the ciphertext.
        return DataKey(key_id=self._active, plaintext=self._keys[self._active], wrapped=b"")

    def unwrap(self, key_id: str, wrapped: bytes) -> bytes:
        key = self._keys.get(key_id)
        if key is None:
            # Named explicitly. "Decryption failed" would send somebody hunting
            # for corruption when the real answer is that a key was removed from
            # configuration while rows still referenced it.
            raise SecretsError(
                f"No encryption key configured with id '{key_id}'. "
                "A key that still has rows encrypted under it must not be removed."
            )
        return key


class AwsKmsKeyProvider:
    """Envelope encryption against AWS KMS.

    One `GenerateDataKey` call per encryption and one `Decrypt` per read. That
    is a network round trip per operation, which is why this is used for
    low-volume, high-value columns — a TOTP secret is read once per login, not
    once per list request. Encrypting a hot column this way would need a data-key
    cache, and a cache of plaintext keys is a different security posture that
    should be an explicit decision rather than a performance patch.
    """

    name = "aws_kms"

    def __init__(self, key_id: str, region: str | None = None) -> None:
        self._key_id = key_id
        self._region = region
        self._client = None

    @property
    def client(self):  # type: ignore[no-untyped-def]
        """Resolved lazily so importing this module needs no AWS credentials."""
        if self._client is None:
            import boto3

            self._client = boto3.client("kms", region_name=self._region)
        return self._client

    def generate(self) -> DataKey:
        try:
            response = self.client.generate_data_key(
                KeyId=self._key_id, KeySpec="AES_256"
            )
        except Exception as exc:  # pragma: no cover — needs a live KMS
            raise SecretsError(f"KMS GenerateDataKey failed: {exc}") from exc
        return DataKey(
            key_id=self._key_id,
            plaintext=response["Plaintext"],
            wrapped=response["CiphertextBlob"],
        )

    def unwrap(self, key_id: str, wrapped: bytes) -> bytes:
        try:
            # KeyId is passed even though the blob identifies its own key: it
            # makes KMS reject a blob encrypted under a *different* key rather
            # than happily decrypting it, which is the difference between a
            # confused-deputy bug and an error.
            response = self.client.decrypt(CiphertextBlob=wrapped, KeyId=key_id)
        except Exception as exc:  # pragma: no cover — needs a live KMS
            raise SecretsError(f"KMS Decrypt failed: {exc}") from exc
        return bytes(response["Plaintext"])


class SecretBox:
    """Seals and opens values with keys from a provider."""

    def __init__(self, provider: KeyProvider) -> None:
        self.provider = provider

    def encrypt(self, plaintext: str, *, context: str = "") -> str:
        """Seal a value into a self-describing token.

        `context` is bound into the ciphertext as associated data, so a token
        cannot be lifted out of one column and replayed into another — moving a
        sealed `mfa_secret` into a different field produces an authentication
        failure rather than a working secret in the wrong place.
        """
        from cryptography.hazmat.primitives.ciphers.aead import AESGCM

        key = self.provider.generate()
        nonce = os.urandom(NONCE_BYTES)
        ciphertext = AESGCM(key.plaintext).encrypt(
            nonce, plaintext.encode("utf-8"), _aad(key.key_id, context)
        )
        return ".".join(
            (
                TOKEN_PREFIX,
                key.key_id,
                _b64(key.wrapped),
                _b64(nonce),
                _b64(ciphertext),
            )
        )

    def decrypt(self, token: str, *, context: str = "") -> str:
        """Open a token. A value that is not a token is returned unchanged.

        See the module docstring: that fallback is the migration path off the
        plaintext this feature ships on top of, not a silent failure mode. It is
        logged, once per read, so the plaintext population is observable as it
        drains.
        """
        if not is_token(token):
            logger.info("secret_read_as_plaintext", extra={"context": context or "unknown"})
            return token

        from cryptography.hazmat.primitives.ciphers.aead import AESGCM

        try:
            _, key_id, wrapped, nonce, ciphertext = token.split(".", 4)
        except ValueError as exc:
            raise SecretsError("Malformed secret token.") from exc

        key = self.provider.unwrap(key_id, _unb64(wrapped))
        try:
            opened = AESGCM(key).decrypt(
                _unb64(nonce), _unb64(ciphertext), _aad(key_id, context)
            )
        except Exception as exc:
            # AES-GCM is authenticated, so this is a tampered or misfiled value
            # rather than garbage that decrypted to something plausible.
            raise SecretsError("Secret failed authentication — it has been altered.") from exc
        return opened.decode("utf-8")


def is_token(value: str) -> bool:
    return value.startswith(f"{TOKEN_PREFIX}.")


def _aad(key_id: str, context: str) -> bytes:
    return f"{TOKEN_PREFIX}|{key_id}|{context}".encode()


def _b64(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).decode("ascii")


def _unb64(value: str) -> bytes:
    return base64.urlsafe_b64decode(value.encode("ascii"))


# ------------------------------------------------------------- resolution


def build_key_provider(settings: Settings | None = None) -> KeyProvider:
    resolved = settings or get_settings()

    if resolved.ENCRYPTION_PROVIDER == "aws_kms":
        if not resolved.KMS_KEY_ID:
            raise SecretsError("ENCRYPTION_PROVIDER is 'aws_kms' but KMS_KEY_ID is unset.")
        return AwsKmsKeyProvider(resolved.KMS_KEY_ID, resolved.kms_region)

    keys = _parse_local_keys(resolved)
    # When nothing was configured the only key is the derived one, so the
    # active id follows it rather than requiring a second variable to be set in
    # step with the first.
    active = (
        DERIVED_KEY_ID
        if set(keys) == {DERIVED_KEY_ID}
        else resolved.ENCRYPTION_ACTIVE_KEY_ID
    )
    return LocalKeyProvider(keys, active)


def _parse_local_keys(settings: Settings) -> dict[str, bytes]:
    """`id:base64,id:base64` into usable key material.

    Derived rather than accepted verbatim: a 32-byte key given as a passphrase
    would be a low-entropy key that looks like a proper one, so the material is
    required to be base64 of exactly `KEY_BYTES`.
    """
    raw = settings.ENCRYPTION_KEYS.get_secret_value().strip()
    if not raw:
        # Derived from JWT_SECRET rather than absent, so a developer clone
        # encrypts by default instead of silently storing plaintext until
        # somebody remembers to set a variable. JWT_SECRET is already a
        # required, 32-character, environment-managed secret, so this adds no
        # new key-management surface — it reuses the one that exists.
        #
        # The cost is real and is why production refuses the `local` provider
        # outright: rotating JWT_SECRET makes every value sealed under the
        # derived key unreadable. The key id says `jwt-derived` in every token
        # so that is diagnosable rather than mysterious.
        return {DERIVED_KEY_ID: _derive_key(settings.JWT_SECRET.get_secret_value())}

    keys: dict[str, bytes] = {}
    for entry in raw.split(","):
        entry = entry.strip()
        if not entry:
            continue
        key_id, _, material = entry.partition(":")
        if not key_id or not material:
            raise SecretsError("ENCRYPTION_KEYS entries must be 'id:base64-key'.")
        try:
            decoded = base64.urlsafe_b64decode(_pad(material))
        except Exception as exc:
            raise SecretsError(f"Encryption key '{key_id}' is not valid base64.") from exc
        if len(decoded) != KEY_BYTES:
            raise SecretsError(
                f"Encryption key '{key_id}' is {len(decoded)} bytes; {KEY_BYTES} required. "
                "Generate one with: openssl rand -base64 32"
            )
        keys[key_id.strip()] = decoded
    return keys


def _derive_key(material: str) -> bytes:
    """HKDF a 32-byte key from an existing secret.

    HKDF rather than a raw hash: the input is a passphrase-shaped secret, and
    HKDF's extract-then-expand is what turns that into uniform key material with
    a domain separator, so this key cannot collide with any other use of
    JWT_SECRET.
    """
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.kdf.hkdf import HKDF

    return HKDF(
        algorithm=hashes.SHA256(),
        length=KEY_BYTES,
        salt=None,
        info=b"vantage-crm/secrets/v1",
    ).derive(material.encode("utf-8"))


def _pad(value: str) -> str:
    return value + "=" * (-len(value) % 4)


@lru_cache(maxsize=1)
def get_secret_box() -> SecretBox:
    """The process-wide box. Cached like `get_settings`."""
    return SecretBox(build_key_provider())


def reset_secret_box() -> None:
    """Drop the cached box. For tests and for a config reload."""
    get_secret_box.cache_clear()


def encryption_configured(settings: Settings | None = None) -> bool:
    """Whether sealing would work, without raising.

    Used by the production readiness check and the admin health panel, both of
    which want to *report* a misconfiguration rather than crash on it.
    """
    try:
        build_key_provider(settings)
    except SecretsError:
        return False
    return True


__all__ = [
    "KEY_BYTES",
    "TOKEN_PREFIX",
    "AwsKmsKeyProvider",
    "DataKey",
    "KeyProvider",
    "LocalKeyProvider",
    "SecretBox",
    "SecretsError",
    "build_key_provider",
    "encryption_configured",
    "get_secret_box",
    "is_token",
    "reset_secret_box",
]
